# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43c5f8335110b12bfe77717f33c3f881fb3492422ff4177250c5406744b23c812f15031fe06fe66f28d287715663feb5f9c04b5536f3767552b52486f693dde9
  facebook_app_id: 1706470739627166
  facebook_app_secret: b93aff41dcba96f82c3be8e071d4b91f


test:
  secret_key_base: 8b1a63ba5b67466843b13d3b5875d996256236ce7712ed1c588a4731401f28e06803decde86cbb8feae500152722440b89a7abac0df83bafffbc2f8672b0c534

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
